name: Run Backend

on:
  workflow_dispatch: # esto crea el botón "Run workflow"

jobs:
  run-server:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: cookcost
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Wait for MySQL service to be ready
        run: |
          # Espera a que el servicio de MySQL esté listo antes de continuar
          for i in $(seq 1 10); do
            nc -z localhost 3306 && break || sleep 5
          done

      - name: Load database schema
        run: |
          mysql --user=root --password=${{ secrets.MYSQL_ROOT_PASSWORD }} cookcost < structure.sql    

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run server
        run: node index.js
